# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-10 10:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(verbose_name='Content id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectPermissionInheritanceBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(verbose_name='Content id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('content_types', models.ManyToManyField(blank=True, related_name='content_types', to='contenttypes.ContentType', verbose_name='Content Types')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalRoleRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Content id')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('codename', models.CharField(max_length=100, unique=True, verbose_name='Codename')),
                ('global_permissions', models.ManyToManyField(blank=True, related_name='roles_globals', to='permissions.Permission', verbose_name='Global permissions')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='principalrolerelation',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Role', verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='principalrolerelation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='objectpermissioninheritanceblock',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='objectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='objectpermission',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.Role', verbose_name='Role'),
        ),
        migrations.AlterUniqueTogether(
            name='objectpermission',
            unique_together=set([('role', 'permission', 'content_type', 'content_id')]),
        ),
    ]
